language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_script:
  - npm install
script:
  - node app.js &
  - npm test
before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &1
      repo: arukavina/baking-lyrics-node
    bucket: node-bakinglyrics
    region: "us-east-1"
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: node-bakinglyrics
    key: latest.zip
    bundle_type: zip
    application: baking-lyrics-node
    deployment_group: prd
    region: "us-east-1"
on: *1
after_deploy:
  - forever start app.js
